version: "3.7"
services:
  ##############
  # Local kafka configuration (Kafka, Zookeeper, Kafka-Connect)
  ##############
  kafka:
    image: landoop/fast-data-dev:latest
    container_name: kafka
    ports:
      - 3181:3181
      - 3040:3040
      # - 7081:7081
      - 7082:7082
      - 7083:7083
      - 9092:9092
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
      SAMPLEDATA: 0
      #KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_CONNECT_DEBEZIUM_POSTGRES_VERSION: 1.6.0.Final
      BROKER_PORT: 9092
      REST_PORT: 7082
      CONNECT_PORT: 7083
      ZK_PORT: 3181
      WEB_PORT: 3040
      REGISTRY_PORT: 8081
    restart: always
